# Permalinks
permalink:           pretty

# Setup
title:               Wenye Lin
tagline:             Graduate Student From Tsinghua University. 
url:                 https://linwenye.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Wenye Lin
  url:               https://twitter.com/jamigibbs
  email:             lwy20@mails.tsinghua.edu.cn

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/Linwenye/portfolio
google_analytics:    UA-3363703-15
twitter:             Wenye Lin
github:              Wenye Lin
dribbble:            Wenye Lin

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
